title: Trip Itinerary
description: Trip Planning
theme: https://inducedcandle172.github.io/Itinerary2/

url: https://inducedcandle172.github.io/Itinerary2/

aux_links:
  Template Repository: https://inducedcandle172.github.io/Itinerary2/
